version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: forca_db
    # As variáveis abaixo vêm DIRETAMENTE do seu .env.example
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forca
    ports:
      # Expõe a porta 5432 do container para a porta 5432 da sua máquina
      - "5432:5432"
    volumes:
      # Isso garante que seus dados não sejam perdidos ao reiniciar o container
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: